import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, realpath, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';
import type { ScanSnapshot } from '../../src/contracts.js';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const cli = path.join(project, 'dist', 'wombat.js');

test('命令行优先流程：扫描、概览、用量、环境、检查、会话及按需报告', async () => {
  await stat(cli);
  const root = await mkdtemp(path.join(tmpdir(), 'wombat-e2e-'));
  const workspace = path.join(root, 'my project');
  const codex = path.join(root, '.codex'); const claude = path.join(root, '.claude');
  const dataHome = path.join(root, 'output');
  await mkdir(path.join(codex, 'sessions', '2026', '09', '27'), { recursive: true });
  await mkdir(path.join(claude, 'projects'), { recursive: true });
  await mkdir(workspace, { recursive: true });
  await mkdir(path.join(codex, 'skills', 'sample'), { recursive: true });
  await writeFile(path.join(codex, 'skills', 'sample', 'SKILL.md'), 'Synthetic skill');
  await writeFile(path.join(workspace, 'AGENTS.md'), 'Open [missing](./missing.md).');
  await writeFile(path.join(codex, 'sessions', '2026', '09', '27', 'rollout.jsonl'), JSON.stringify({ timestamp: '2026-09-27T10:00:00Z', type: 'session_meta', payload: { id: 'example', cwd: workspace } }) + '\n');
  const env = { ...process.env, HOME: root, CODEX_HOME: codex, CLAUDE_CONFIG_DIR: claude, WOMBAT_DATA_HOME: dataHome };
  const run = (...args: string[]) => spawnSync(process.execPath, [cli, ...args], { cwd: project, env, encoding: 'utf8', timeout: 30_000 });
  const scan = run('scan', workspace, '--since', '2026-09-27', '--until', '2026-09-28', '--source-dir', `codex=${codex}`, '--source-dir', `claude=${claude}`, '--no-open', '--json');
  assert.equal(scan.status, 0, `${scan.stderr}\n${scan.stdout}`);
  const response = JSON.parse(scan.stdout) as { snapshot: string; report: string };
  assert.equal(response.report, null);
  const snapshot = JSON.parse(await readFile(response.snapshot, 'utf8')) as ScanSnapshot;
  assert.equal(snapshot.scope.workspace, await realpath(workspace));
  assert.ok(snapshot.sessions.some(session => session.id === 'codex:example'));
  assert.ok(snapshot.findings.some(finding => finding.ruleId === 'rules.missing_relative_path'));
  const status = run('status', '--json');
  assert.equal(status.status, 0, status.stderr);
  assert.equal(JSON.parse(status.stdout).summary.resources, snapshot.resources.length);
  const usage = run('usage', 'daily', '--json');
  assert.equal(usage.status, 0, usage.stderr);
  assert.equal(JSON.parse(usage.stdout).kind, 'daily');
  const environment = run('env', '--kind', 'skill', '--json');
  assert.equal(environment.status, 0, environment.stderr);
  assert.ok(JSON.parse(environment.stdout).resources.some((item: { name: string }) => item.name === 'sample'));
  const doctor = run('doctor', '--json');
  assert.equal(doctor.status, 0, doctor.stderr);
  assert.ok(JSON.parse(doctor.stdout).findings.some((item: { ruleId: string }) => item.ruleId === 'rules.missing_relative_path'));
  const sessions = run('sessions', '--json');
  assert.equal(sessions.status, 0, sessions.stderr);
  assert.ok(JSON.parse(sessions.stdout).sessions.some((item: { id: string }) => item.id === 'codex:example'));
  const detail = run('sessions', '--session', 'codex:example', '--json');
  assert.equal(detail.status, 0, detail.stderr);
  assert.equal(JSON.parse(detail.stdout).session.id, 'codex:example');
  const menuFallback = run();
  assert.equal(menuFallback.status, 0);
  assert.match(menuFallback.stdout, /wombat status/);
  const rebuilt = path.join(root, 'rebuilt.html');
  const rereport = run('report', '--snapshot', response.snapshot, '--out', rebuilt, '--no-open', '--json');
  assert.equal(rereport.status, 0, rereport.stderr);
  const report = await readFile(rebuilt, 'utf8');
  assert.ok(report.includes('window.__WOMBAT_SNAPSHOT__='));
  assert.ok(report.includes('本地报告'));
  const rebuiltAgain = path.join(root, 'rebuilt-again.html');
  const rereportAgain = run('report', '--snapshot', response.snapshot, '--out', rebuiltAgain, '--json');
  assert.equal(rereportAgain.status, 0, rereportAgain.stderr);
  assert.equal(await readFile(rebuiltAgain, 'utf8'), report);
  const htmlScan = run('scan', workspace, '--since', '2026-09-27', '--until', '2026-09-28', '--html', '--no-open', '--json');
  assert.equal(htmlScan.status, 0, htmlScan.stderr);
  assert.ok(JSON.parse(htmlScan.stdout).report);
  const invalid = run('usage', 'daily', '--timezone', 'Wrong/Zone');
  assert.equal(invalid.status, 1);
  assert.match(invalid.stderr, /无效时区/);
  const unsupported = run('scan', workspace, '--source-dir', 'unknown=/tmp', '--no-open');
  assert.equal(unsupported.status, 1);
  assert.match(unsupported.stderr, /不支持 --source-dir 来源/);
  const wrongFlag = run('status', '--kind', 'skill');
  assert.equal(wrongFlag.status, 1);
  assert.match(wrongFlag.stderr, /不支持 --kind/);
});
