import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,realpath,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {once} from 'node:events';
import {createNodeClient} from '@wombat/client/node';
import {createHttpClient} from '@wombat/client/http';
import {startWebHost} from '@wombat/web';
import type {OptimizeRequest} from '@wombat/client';

test('static configuration reviews, manual recheck, all dates and preferences share CLI/Web contracts', {timeout:45_000},async()=>{
 const dir=await realpath(await mkdtemp(path.join(tmpdir(),'wombat-upgrade-e2e-'))),root=path.join(dir,'source'),project=path.join(dir,'project'),data=path.join(dir,'data'),skill=path.join(project,'.agents/skills/example/SKILL.md');
 await mkdir(path.join(root,'sessions'),{recursive:true});await mkdir(path.dirname(skill),{recursive:true});
 const large=`---\nname: example\ndescription: ${'字'.repeat(501)}\n---\n${'x '.repeat(4999)+'x'}`;
 await writeFile(skill,large);await writeFile(path.join(project,'AGENTS.md'),'你好，世界！\r\n');
 const row=(type:string,payload:object,timestamp?:string)=>({type,payload,...(timestamp?{timestamp}:{})});
 const usage={input_tokens:100,cached_input_tokens:20,output_tokens:10,total_tokens:110};
 const rows=[row('session_meta',{id:'t',cwd:project},'2026-09-29T00:00:00Z'),row('turn_context',{turn_id:'u',cwd:project,model:'gpt-5.4'},'2026-09-29T00:00:00Z'),row('event_msg',{type:'task_started',turn_id:'u'},'2026-09-29T00:00:00Z'),...['2026-09-29T23:59:00Z','2026-09-30T00:01:00Z',undefined].map((at,n)=>row('event_msg',{type:'token_usage_record',thread_id:'t',turn_id:'u',response_id:`r${n}`,usage},at))];
 rows.push(...['read-skill-1','read-skill-2'].flatMap(call_id=>[row('response_item',{type:'function_call',call_id,name:'read_file',arguments:JSON.stringify({path:skill})},'2026-09-29T00:00:00Z'),row('response_item',{type:'function_call_output',call_id,output:'Synthetic content'},'2026-09-29T00:00:00Z')]));
 rows.push(row('session_meta',{id:'nested-reader',cwd:path.join(project,'nested')},'2026-09-29T00:00:00Z'),row('response_item',{type:'function_call',call_id:'nested-read',name:'read_file',arguments:JSON.stringify({path:path.join(project,'AGENTS.md')})},'2026-09-29T00:00:00Z'));
 await writeFile(path.join(root,'sessions/log.jsonl'),rows.map(r=>JSON.stringify(r)).join('\n')+'\n');
 const saved={WOMBAT_DATA_HOME:process.env.WOMBAT_DATA_HOME,CODEX_HOME:process.env.CODEX_HOME,WOMBAT_AUTO_PRICES:process.env.WOMBAT_AUTO_PRICES};Object.assign(process.env,{WOMBAT_DATA_HOME:data,CODEX_HOME:root,WOMBAT_AUTO_PRICES:'0'});
 const binary=path.resolve('dist',process.platform==='win32'?'wombat-core.exe':'wombat-core'),service=spawn(binary,['--serve-usage'],{stdio:'ignore',env:process.env});await once(service,'spawn');
 const client=createNodeClient({binaryPath:binary}),host=await startWebHost({client,assets:path.resolve('dist/web'),roots:[root],projectRoots:[project]});
 const http=(origin:string,url:string)=>createHttpClient({origin,token:new URLSearchParams(new URL(url).hash.slice(1)).get('token')!,fetch:(url,init)=>fetch(url,{...init,headers:{...init?.headers,Origin:origin}})}),browser=http(host.origin,host.url);
 try{
  const all=await browser.live!({query:{action:'usage',scope:{allTime:true,timezone:'UTC'}},mode:'fresh'});assert.equal(all.result.summary.tokens.total,330);assert.ok(all.result.items.some(i=>i.kind==='usage'&&i.date==null),'all dates explicitly includes undated usage');
  const day=await browser.live!({query:{action:'usage',scope:{since:'2026-09-29',until:'2026-09-30',timezone:'UTC'},snapshotId:all.result.snapshotRef.snapshotId},mode:'cached'});assert.equal(day.result.summary.tokens.total,110);
  const config=await browser.config!({action:'list',scope:{allTime:true,timezone:'UTC'}}),item=config.items.find(i=>i.kind==='skill')!;
  assert.equal(item.bytes,Buffer.byteLength(large));assert.equal(item.characters,[...large].length);assert.equal(item.skillMetadata?.descriptionCharacters,501);assert.equal(item.skillMetadata?.status,'parsed');assert.ok(item.contentTokens!>0);assert.equal(item.estimate?.contentHash,item.contentHash);assert.equal(item.bodyTokenEstimate?.tokens,5000);assert.equal(item.bodyTokenEstimate?.payload,'skillBody');assert.notEqual(item.bodyTokenEstimate?.contentHash,item.contentHash);assert.equal(item.bodyTokenEstimate?.tokenizerVersion,'tiktoken-rs-0.12.0');assert.equal(item.usageCount,null);assert.equal(config.items.find(i=>i.path===path.join(project,'AGENTS.md'))!.usageCount,null);assert.equal(config.items.find(i=>i.path===path.join(project,'AGENTS.md'))!.counts.fileReads,1,'an explicit exact-path read remains evidence even from a nested cwd');
  const first=await browser.optimize!({action:'list'});assert.equal(first.pending,1);assert.equal(first.suggestions[0].findings.length,2);assert.equal(first.suggestions[0].category,'trim');
  assert.equal(first.ruleParameters.version,'static-config-v4');assert.deepEqual(first.suggestions[0].findings.map(f=>f.rule),['descriptionSize','bodyTokens']);
  const related=await browser.config!({action:'evidence',readView:first.readView,itemId:item.id,scope:{allTime:true,timezone:'UTC'}});assert.equal(related.items[0].counts.fileReads,2);assert.equal(related.items[0].relatedTurns,1);assert.equal(related.items[0].usage?.tokens.total,330,'repeated reads do not multiply the associated ledger');assert.equal(related.evidence[0].turnId,related.evidence[1].turnId);
  const cliRelated=spawnSync(process.execPath,[path.resolve('dist/wombat.js'),'optimize','inventory','--root',root,'--project-root',project,'--action','evidence','--item',item.id,'--read-view',first.readView!,'--all-time','--timezone','UTC','--json'],{env:process.env,encoding:'utf8',timeout:10_000});assert.equal(cliRelated.status,2,cliRelated.stderr+cliRelated.stdout);assert.deepEqual(JSON.parse(cliRelated.stdout).evidence,related.evidence);
  const exact=await browser.live!({query:{action:'turns',snapshotId:related.usageRevision,threadId:related.evidence[0].threadId,locateTurnId:related.evidence[0].turnId,scope:{allTime:true}},mode:'cached'});assert.equal(exact.result.items.find(i=>i.kind==='turn')?.id,related.evidence[0].turnId);assert.equal(exact.result.summary.tokens.total,330);
  const noRelated=await browser.config!({action:'evidence',readView:first.readView,itemId:item.id,scope:{since:'2026-10-01',until:'2026-10-02',timezone:'UTC'}});assert.equal(noRelated.evidence.length,0);assert.equal(noRelated.items[0].usage,null);assert.equal((await browser.optimize!({action:'list',readView:first.readView})).pending,1,'record dates do not change the current checks');
  const overridden=await browser.optimize!({action:'list',readView:first.readView,ruleOverrides:{descriptionCharacters:600}});assert.deepEqual(overridden.suggestions[0].findings.map(f=>f.rule),['bodyTokens']);
  const cliSame=spawnSync(process.execPath,[path.resolve('dist/wombat.js'),'optimize','list','--root',root,'--project-root',project,'--read-view',first.readView!,'--description-characters','600','--json'],{env:process.env,encoding:'utf8',timeout:10_000});assert.equal(cliSame.status,2,cliSame.stderr+cliSame.stdout);assert.deepEqual(JSON.parse(cliSame.stdout).suggestions,overridden.suggestions);
  const pinned:OptimizeRequest={readView:first.readView,decisionRevision:first.decisionRevision};
  const ignored=await browser.optimize!({...pinned,action:'ignore',suggestionId:first.suggestions[0].id});assert.equal(ignored.pending,0);
  await assert.rejects(browser.optimize!({...pinned,action:'list'}),{code:'VIEW_EXPIRED'});
  await rm(path.join(data,'config-v1'),{recursive:true,force:true});assert.equal((await browser.optimize!({action:'list'})).pending,0,'derived inventory rebuild retains ignore decisions');
  await writeFile(skill,`---\nname: []\ndescription: sample\n---\n${'x '.repeat(4999)+'x'}`);
  const changed=await browser.optimize!({action:'list'});assert.equal(changed.pending,1);assert.equal(changed.suggestions[0].category,'repair');assert.notEqual(changed.suggestions[0].id,first.suggestions[0].id);
  const marked=await browser.optimize!({action:'mark_edited',readView:changed.readView,decisionRevision:changed.decisionRevision,suggestionId:changed.suggestions[0].id});assert.equal(marked.suggestions[0].status,'awaitingRecheck');assert.equal(marked.suggestions[0].reviewBaseline?.contentHash,changed.suggestions[0].item.contentHash);
  await rm(skill);
  const removed=await browser.optimize!({action:'recheck',group:'history'});
  assert.equal(removed.suggestions[0].status,'recheckUnavailable','complete historical metadata cannot verify a removed source file');
  assert.equal(removed.suggestions[0].item.current,false);
  assert.equal(removed.suggestions[0].reviewBaseline?.contentHash,changed.suggestions[0].item.contentHash);
  const removedAgain=await browser.optimize!({action:'recheck',group:'history'});
  assert.equal(removedAgain.suggestions[0].status,'recheckUnavailable');
  await writeFile(skill,Buffer.from([255,254]));
  const unreadable=await browser.optimize!({action:'recheck',readView:removedAgain.readView,decisionRevision:removedAgain.decisionRevision,group:'history'});assert.equal(unreadable.suggestions[0].status,'recheckUnavailable');assert.equal(unreadable.suggestions[0].item.contentTokens,null);assert.equal(unreadable.suggestions[0].item.bodyTokenEstimate,null);assert.equal(unreadable.suggestions[0].item.bytes,2);
  const fixed='---\nname: example\ndescription: Synthetic sample\n---\nUse evidence.\n';await writeFile(skill,fixed);
  const checked=await browser.optimize!({action:'recheck',readView:unreadable.readView,decisionRevision:unreadable.decisionRevision,group:'history'});assert.equal(checked.pending,0);assert.equal(checked.suggestions[0].status,'verified');assert.ok(checked.history>=4);assert.equal(checked.suggestions[0].reviewBaseline?.contentHash,changed.suggestions[0].item.contentHash);assert.notEqual(checked.suggestions[0].reviewBaseline?.contentHash,checked.suggestions[0].item.contentHash);
  const now=await browser.config!({action:'detail',readView:checked.readView,itemId:item.id,scope:{allTime:true}});assert.equal(now.items[0].contentHash,checked.suggestions[0].item.contentHash);assert.equal(now.items[0].bytes,Buffer.byteLength(fixed));
  const old=await browser.config!({action:'detail',readView:config.readView,itemId:item.id,scope:{allTime:true}});assert.equal(old.items[0].contentHash,item.contentHash);
  const historic=await browser.live!({query:{action:'usage',snapshotId:config.usageRevision,scope:{allTime:true}},mode:'cached'});assert.equal(historic.result.summary.tokens.total,330);
  const metadataHeavy=`---\nname: example\ndescription: valid\n# ${'x '.repeat(10000)}\n---\nhello world`;await writeFile(skill,metadataHeavy);
  const metadataConfig=await browser.config!({action:'list'}),metadataItem=metadataConfig.items.find(i=>i.kind==='skill')!;assert.ok(metadataItem.bytes!>16384);assert.ok(metadataItem.contentTokens!>5000);assert.equal(metadataItem.bodyTokenEstimate?.tokens,2);assert.equal((await browser.optimize!({action:'list',readView:metadataConfig.readView})).pending,0,'large metadata/full file does not substitute for body measurement');
  const descriptionTooLong=`---\nname: example\ndescription: ${'😀'.repeat(1025)}\n---\n${'x '.repeat(4999)}x`;await writeFile(skill,descriptionTooLong);
  const standard=await browser.optimize!({action:'list',ruleOverrides:{descriptionCharacters:1024}});assert.equal(standard.pending,1);assert.equal(standard.suggestions[0].category,'repair');assert.deepEqual(standard.suggestions[0].findings.map(f=>f.rule),['descriptionStandard','bodyTokens']);assert.equal(standard.suggestions[0].findings[0].observed,1025);
  await browser.optimize!({action:'mark_edited',suggestionId:standard.suggestions[0].id,readView:standard.readView,decisionRevision:standard.decisionRevision,ruleOverrides:{descriptionCharacters:1024}});
  await writeFile(skill,descriptionTooLong.replace('😀'.repeat(1025),'😀'.repeat(730)));
  const trimmed=await browser.optimize!({action:'recheck',group:'history'});assert.equal(trimmed.suggestions[0].status,'stillNeedsReview');
  const remaining=await browser.optimize!({action:'list',readView:trimmed.readView});assert.equal(remaining.pending,1);assert.equal(remaining.suggestions[0].category,'trim');assert.deepEqual(remaining.suggestions[0].findings.map(f=>f.rule),['descriptionSize','bodyTokens']);
  await writeFile(skill,fixed);const final=await browser.optimize!({action:'recheck',group:'history'});assert.equal(final.pending,0);assert.equal(final.suggestions[0].status,'verified');
  for(const bad of[{roots:[dir]},{projectRoots:[dir]},{readView:'config:foreign'},{action:'execute'},{ruleOverrides:{descriptionCharacters:1025}},{ruleOverrides:{bodyTokens:10000}}])await assert.rejects(browser.optimize!({action:'list',...bad} as OptimizeRequest),{code:'INVALID_ARGUMENT'});
  await assert.rejects(browser.optimize!({action:'ignore',suggestionId:'missing'}),{code:'NOT_FOUND'});
  const cli=spawnSync(process.execPath,[path.resolve('dist/wombat.js'),'optimize','history','--root',root,'--project-root',project,'--read-view',checked.readView!,'--json'],{env:process.env,encoding:'utf8',timeout:10_000});assert.equal(cli.status,2,cli.stderr+cli.stdout);assert.deepEqual(JSON.parse(cli.stdout).suggestions,(await browser.optimize!({action:'list',group:'history',readView:checked.readView})).suggestions);
  const cliAll=spawnSync(process.execPath,[path.resolve('dist/wombat.js'),'usage','--snapshot',all.result.snapshotRef.snapshotId,'--all-time','--json'],{env:process.env,encoding:'utf8',timeout:10_000});assert.equal(cliAll.status,0,cliAll.stderr+cliAll.stdout);assert.equal(JSON.parse(cliAll.stdout).summary.tokens.total,330);
  const caps=await browser.optimize!({action:'capabilities'});assert.equal(caps.capabilities.inactivity,false);assert.equal(caps.capabilities.spaceCleanup,false);assert.equal(caps.capabilities.loadingBudgetDiagnosis,false);for(const category of ['organize','space'] as const){const unavailable=await browser.optimize!({action:'list',category});assert.equal(unavailable.suggestions.length,0);assert.equal(unavailable.resultStatus,'partial');}
  assert.equal((await browser.preferences!({action:'get'})).language,null);await browser.preferences!({action:'set',language:'en'});
  assert.equal(await readFile(path.join(data,'user-v1/language.json'),'utf8'),'"en"');
  await host.close();const second=await startWebHost({client:createNodeClient({binaryPath:binary}),assets:path.resolve('dist/web'),roots:[root],projectRoots:[project]});try{assert.equal((await http(second.origin,second.url).preferences!({action:'get'})).language,'en');assert.equal(new URLSearchParams(new URL(second.url).hash.slice(1)).get('lang'),null);}finally{await second.close();}
 }finally{await host.close();if(service.exitCode===null){const exited=once(service,'close');service.kill();await exited;}for(const[key,value]of Object.entries(saved))if(value===undefined)delete process.env[key];else process.env[key]=value;await rm(dir,{recursive:true,force:true,maxRetries:10,retryDelay:100});}
});
