import { useEffect, useRef, useState } from 'react';
import type { OptimizeRequest, OptimizeResult, OptimizeSuggestion, UsageClient } from '@wombat/client';
import { t, reviewFindingLabel, reviewFindingNote, reviewPresentation } from '@wombat/client/locale';
import { Empty, Heading, Modal, Pagination, Token, timestamp } from './components.js';
import { QueryError } from './Feedback.js';
import {detailReturnRoute, routeSearch, type Route} from './state.js';
import { ReviewUsage, TextChanges } from './ReviewUsage.js';
import './config.css';
export function useOptimize(client:UsageClient,request:OptimizeRequest){
 const key=JSON.stringify(request),[retry,setRetry]=useState(0),active=useRef<AbortController|undefined>(undefined);
 const [state,setState]=useState<{key?:string;data?:OptimizeResult;loading:boolean;error?:string;code?:string}>({loading:true});
 useEffect(()=>{const c=new AbortController();active.current=c;setState({key,loading:true});
 void (client.optimize?client.optimize(JSON.parse(key),{signal:c.signal}):Promise.reject(new Error(t('webui.unsupported')))).then(data=>{if(!c.signal.aborted)setState({key,data,loading:false});},e=>{if(!c.signal.aborted)setState({key,loading:false,error:String(e.message??e),code:e.code});});return()=>c.abort();},[client,key,retry]);
 return {...(state.key===key?state:{loading:true}),retry:()=>setRetry(n=>n+1),cancel:()=>{active.current?.abort();setState({key,loading:false,error:'CANCELLED',code:'CANCELLED'});}};
}
export function OptimizeSummary({client,route,navigate}:{client:UsageClient;route:Route;navigate:(r:Partial<Route>)=>void}){
 const q=useOptimize(client,{action:'list',project:route.project,sourceInstanceId:route.source,limit:3,ruleOverrides:{agentsBytes:route.agentsBytes,descriptionCharacters:route.descriptionCharacters}});
 return <section className="panel optimize-summary"><h2>{t('optimize.summary')}</h2>{q.loading?<p role="status">{t('webui.loading')}</p>:q.error?<QueryError error={q.error} code={q.code} retry={q.retry}/>:q.data?<><p>{t('optimize.summaryCount',{pending:q.data.pending,history:q.data.history})}</p>{q.data.suggestions.map(s=>{const p=reviewPresentation(s);return <button className="config-row review-row" key={s.id} onClick={()=>navigate({page:'optimize',optimizeView:q.data!.readView??undefined,decisionRevision:q.data!.decisionRevision,suggestion:s.id,suggestionRecord:s.recordId??undefined,optimizeCategory:undefined,optimizeGroup:'pending',optimizeOffset:0})}><span className="config-identity"><strong>{p.title}</strong><span className="review-value">{p.value}</span></span><span className="config-metric">{p.metric?.toLocaleString()??'—'}<small>{p.label}</small></span></button>;})}<button onClick={()=>navigate({page:'optimize',optimizeView:q.data!.readView??undefined,decisionRevision:q.data!.decisionRevision,suggestion:undefined,suggestionRecord:undefined,optimizeOffset:0,optimizeGroup:'pending'})}>{t('optimize.viewAll')}</button><p className="note">{t('optimize.note')}</p></>:null}</section>;
}
export function OptimizeView({client,route,navigate,pin}:{client:UsageClient;route:Route;navigate:(r:Partial<Route>)=>void;pin:(view:string,revision:string)=>void}){
 const request:OptimizeRequest={action:'list',readView:route.optimizeView,decisionRevision:route.decisionRevision,project:route.project,sourceInstanceId:route.source,group:route.optimizeGroup??'pending',category:route.optimizeCategory,offset:route.optimizeOffset??0,limit:30,ruleOverrides:{agentsBytes:route.agentsBytes,descriptionCharacters:route.descriptionCharacters}};
 const q=useOptimize(client,request),navRef=useRef(pin);navRef.current=pin;
 const [busy,setBusy]=useState(false),[error,setError]=useState<{message:string;code?:string}>(),[copy,setCopy]=useState<string>();
 const mutation=useRef<AbortController|undefined>(undefined);
 useEffect(()=>()=>mutation.current?.abort(),[]);
 useEffect(()=>{setError(undefined);setCopy(undefined);},[route.suggestion,route.project,route.source]);
 useEffect(()=>{if(q.data&&!route.optimizeView)navRef.current(q.data.readView!,q.data.decisionRevision);},[q.data,route.optimizeView]);
 const refresh=()=>navigate({optimizeView:undefined,decisionRevision:undefined,suggestion:undefined,suggestionRecord:undefined,optimizeOffset:0});
 const update=(patch:Partial<Route>)=>navigate({...patch,suggestion:undefined,suggestionRecord:undefined,optimizeOffset:0});
 const run=async(action:OptimizeRequest['action'],suggestionId?:string)=>{
  if(!q.data||!client.optimize)return;
  const c=new AbortController();mutation.current=c;setBusy(true);setError(undefined);
  try{const result=await client.optimize({...request,action,suggestionId,readView:q.data.readView??undefined,decisionRevision:q.data.decisionRevision,offset:0},{signal:c.signal});if(!c.signal.aborted)navigate({optimizeView:result.readView??undefined,decisionRevision:result.decisionRevision,suggestion:undefined,suggestionRecord:undefined,optimizeOffset:0,configView:undefined,optimizeGroup:action==='recheck'?'history':route.optimizeGroup});}
  catch(e){if(!c.signal.aborted){const err=e as Error&{code?:string};setError({message:err.message,code:err.code});}}finally{if(mutation.current===c)setBusy(false);}
 };
 const result=q.data,selected=result?.suggestions.find(s=>s.id===route.suggestion&&(!route.suggestionRecord||s.recordId===route.suggestionRecord));
 if(route.unassigned)return <Empty title={t('optimize.empty')} copy={t('config.emptyHint')}/>;
 return <>
 <Heading title={t('optimize.title')} sub={t('optimize.note')}><div className="controls"><button disabled={busy} onClick={q.loading?q.cancel:refresh}>{t(q.loading?'webui.cancel':'config.refresh')}</button><button disabled={busy||q.loading||!result} onClick={()=>void run('recheck')}>{t('optimize.recheck')}</button></div></Heading>
 {q.loading&&<p role="status">{t('webui.loading')}</p>}{q.error&&<QueryError error={q.error} code={q.code} retry={q.code==='VIEW_EXPIRED'||q.code==='NOT_FOUND'?refresh:q.retry}/>}{error&&<QueryError error={error.message} code={error.code} retry={refresh}/>}
 {busy&&<p role="status">{t('webui.loading')}</p>}
 {result&&<><details className="provenance"><summary>{t('optimize.ruleSettings')}</summary><p>{t('optimize.ruleSettingsNote')}</p><form key={`${route.agentsBytes}:${route.descriptionCharacters}`} className="controls" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);navigate({agentsBytes:Number(data.get('agentsBytes')),descriptionCharacters:Number(data.get('descriptionCharacters')),optimizeView:undefined,decisionRevision:undefined,suggestion:undefined,suggestionRecord:undefined,optimizeOffset:0});}}><label>{t('optimize.agentsBytes')}<input name="agentsBytes" type="number" min="1" max={Number.MAX_SAFE_INTEGER} step="1" required defaultValue={route.agentsBytes??result.ruleParameters.agentsBytesDefault}/></label><label>{t('optimize.descriptionCharacters')}<input name="descriptionCharacters" type="number" min="0" max="1024" step="1" required defaultValue={route.descriptionCharacters??result.ruleParameters.descriptionCharactersDefault}/></label><button disabled={busy}>{t('optimize.applyRules')}</button><button type="button" disabled={busy} onClick={()=>navigate({agentsBytes:undefined,descriptionCharacters:undefined,optimizeView:undefined,decisionRevision:undefined,suggestion:undefined,suggestionRecord:undefined,optimizeOffset:0})}>{t('optimize.defaultRules')}</button></form><p><code>{result.ruleParameters.version}</code></p></details><div className="config-toolbar"><nav className="config-types" aria-label={t('optimize.title')}>{(['pending','history'] as const).map(group=><button key={group} disabled={busy} aria-pressed={(route.optimizeGroup??'pending')===group} onClick={()=>update({optimizeGroup:group})}>{t(`optimize.${group}`)} · {result[group]}</button>)}</nav><select aria-label={t('optimize.title')} value={route.optimizeCategory??''} disabled={busy} onChange={e=>update({optimizeCategory:e.target.value as Route['optimizeCategory']||undefined})}><option value="">{t('config.all')}</option>{(['repair','trim','organize','space'] as const).map(c=><option key={c} value={c}>{t(`optimize.${c}`)}</option>)}</select><span className="note">{timestamp(result.checkedAt,route.timezone)}</span></div>
 <section className="panel config-list review-list" aria-label={t('optimize.title')}>{result.suggestions.map(s=>{const presentation=reviewPresentation(s);return <button key={s.recordId??s.id} className={`config-row review-row ${selected===s?'active':''}`} disabled={busy} aria-current={selected===s?'true':undefined} onClick={()=>navigate({suggestion:s.id,suggestionRecord:s.recordId??undefined})}><span className="config-identity"><span className="config-kind">{t(`optimize.${s.category}`)}</span><strong>{presentation.title}</strong><span className="review-value">{presentation.value}</span>{route.optimizeGroup==='history'&&<span className="tag">{statusLabel(s.status)}</span>}</span><span className="config-metric"><span>{presentation.metric?.toLocaleString()??'—'}</span><small>{presentation.label}</small></span></button>;})}{!result.suggestions.length&&<Empty title={t('optimize.empty')} copy={t(route.optimizeCategory==='organize'?'optimize.organizeUnavailable':route.optimizeCategory==='space'?'optimize.spaceUnavailable':'optimize.emptyNote')}/>}<Pagination page={result.page} onPage={optimizeOffset=>navigate({optimizeOffset,suggestion:undefined,suggestionRecord:undefined})}/></section>
 {selected&&<Modal key={selected.recordId??selected.id} title={reviewPresentation(selected).title} drawer onClose={()=>navigate({suggestion:undefined,suggestionRecord:undefined})}><div className="review-detail">
 {detailReturnRoute(route)&&<button className="link" onClick={()=>navigate(detailReturnRoute(route)!)}>{t('webui.back')}</button>}<p className="tag">{t(`optimize.${selected.category}`)} · {statusLabel(selected.status)}</p><p><code className="config-path">{selected.item.path}</code></p><button className="link" disabled={busy} onClick={()=>navigate({page:'config',detailReturn:routeSearch({...route,detailReturn:undefined}),configView:result.readView??undefined,configId:selected.item.id,configSearch:undefined,configKind:undefined,configState:undefined,configOffset:0,configThread:undefined})}>{t('optimize.configuration')}</button>
 <section><h3>{t('optimize.suggestionValue')}</h3><p className="review-benefit">{reviewPresentation(selected).value}</p><p>{selected.findings.map(f=>findingLabel(f.rule)).join(' · ')}</p>
 <details className="provenance"><summary>{t('optimize.steps')}</summary><p>{t('optimize.manualNote')}</p><button disabled={busy} onClick={()=>{void (navigator.clipboard?navigator.clipboard.writeText(selected.item.path):Promise.reject(new Error())).then(()=>setCopy(t('optimize.copied')),()=>setCopy(t('optimize.copyFailed')));}}>{t('optimize.copyPath')}</button><p role="status">{copy}</p></details></section>
 {selected.status==='recheckUnavailable'&&<div className="read-notice"><p>{t('optimize.recheckUnavailableHint')}</p><button disabled={busy} onClick={()=>void run('recheck')}>{t('optimize.recheck')}</button></div>}
 <TextChanges suggestion={selected}/>
 <ReviewUsage key={JSON.stringify([selected.item.id,result.readView,route.since,route.until,route.allTime,route.timezone,route.agent,route.source,route.project])} client={client} suggestion={selected} readView={result.readView!} route={route} navigate={navigate} refresh={refresh}/>
 <details className="provenance review-basis"><summary>{t('optimize.basis')}</summary>{route.optimizeGroup==='history'&&<h3>{t('optimize.originalFindings')}</h3>}<Findings suggestion={selected}/>{selected.item.bodyTokenEstimate&&<dl className="facts"><dt>{t('config.bodyTokens')}</dt><dd><Token value={selected.item.bodyTokenEstimate.tokens}/></dd><dt>{t('config.estimateBasis')}</dt><dd><code>{selected.item.bodyTokenEstimate.method}</code></dd><dt>{t('config.bodyHash')}</dt><dd><code>{selected.item.bodyTokenEstimate.contentHash}</code></dd></dl>}<p className="note"><code>{selected.ruleVersion}</code></p><p className="note">{t('optimize.scopeNote')}</p><p className="note">{t('optimize.recordDatesNote')}</p><p className="note">{timestamp(selected.recordedAt??selected.checkedAt,route.timezone)}</p></details>
 {error&&<QueryError error={error.message} code={error.code} retry={refresh}/>}{busy&&<p role="status">{t('webui.loading')}</p>}
 <div className="review-actions">{(route.optimizeGroup??'pending')==='pending'&&<div className="actions"><button disabled={busy||selected.status==='awaitingRecheck'} className="primary" onClick={()=>void run('mark_edited',selected.id)}>{t('optimize.markEdited')}</button><button disabled={busy} onClick={()=>void run('ignore',selected.id)}>{t('optimize.ignore')}</button><button disabled={busy} onClick={()=>void run('recheck')}>{t('optimize.recheck')}</button></div>}{route.optimizeGroup==='history'&&selected.status==='ignored'&&result.suggestions.find(s=>s.id===selected.id)?.recordId===selected.recordId&&<button disabled={busy} onClick={()=>void run('restore',selected.id)}>{t('optimize.restore')}</button>}</div>
 </div></Modal>}

 <details className="provenance config-coverage"><summary>{t('optimize.coverage')}</summary><p>{t('optimize.coverageNote')}</p>{result.issues.map((i,n)=><p key={n}><code>{i.code}</code>{i.path&&<> · <code>{i.path}</code></>}</p>)}<p>{t('config.readVersion',{version:result.readView??'—'})} · {result.decisionRevision}</p></details></>}
 </>;
}
function Findings({suggestion}:{suggestion:OptimizeSuggestion}){return <ul className="finding-list">{suggestion.findings.map((f,index)=><li key={f.rule+index}><strong>{findingLabel(f.rule)}</strong><p>{reviewFindingNote(f.rule)}</p>{f.observed!=null&&<p>{f.observed.toLocaleString()}{f.threshold!=null&&<> / {f.threshold.toLocaleString()}</>}</p>}{f.evidenceCodes.length>0&&<p>{f.evidenceCodes.join(' · ')}</p>}{f.evidence&&<><p>{t(f.evidence.applicability==='sameFileSameHeading'?'optimize.sameFileApplicability':f.evidence.applicability==='userDeclaredCopy'?'optimize.copyNote':'optimize.declaredApplicability')}</p>{f.evidence.declarationHash&&<p>{t('optimize.declarationBasis')}: <code>{f.evidence.declarationHash}</code> · {f.evidence.relationId}</p>}<h4>{t('optimize.fileVersions')}</h4>{f.evidence.versions.map(v=><p key={v.itemId}><code>{v.path}</code><br/><code>{v.contentHash}</code></p>)}{f.evidence.positions.length>0&&<><h4>{t('optimize.positions')}</h4>{f.evidence.positions.map((p,n)=><p key={n}><code>{f.evidence!.versions.find(v=>v.itemId===p.itemId)?.path}</code> · {p.startLine}–{p.endLine} / [{p.startByte}, {p.endByte})</p>)}</>}<p className="note"><code>{f.evidence.method}</code>{f.evidence.direction&&<> · <code>{f.evidence.direction}</code> · <code>{f.evidence.transform}</code></>}</p></>}</li>)}</ul>;}
export function statusLabel(status:string){switch(status){case 'ignored':return t('optimize.ignored');case 'restored':return t('optimize.restored');case 'awaitingRecheck':return t('optimize.awaitingRecheck');case 'verified':return t('optimize.verified');case 'stillNeedsReview':return t('optimize.stillNeedsReview');case 'recheckUnavailable':return t('optimize.recheckUnavailable');default:return t('optimize.pending');}}
export const findingLabel = reviewFindingLabel;
