import type { OptimizeRequest, UsageClient } from '@wombat/client';
import { reviewPresentation, t } from '@wombat/client/locale';
import { useEffect, useRef } from 'react';
import { Empty, Heading, Pagination, timestamp } from './components.js';
import './config.css';
import { QueryError } from './Feedback.js';
import { reviewStateLabel } from './optimize/presentation.js';
import { SuggestionDetail } from './optimize/SuggestionDetail.js';
import { SuggestionMetric } from './optimize/SuggestionMetric.js';
import { HandoffButton } from './optimize/Handoff.js';
import { type Route } from './state.js';
import { useOptimize } from './useOptimize.js';
import { useReviewActions } from './optimize/useReviewActions.js';
export { findingLabel, statusLabel } from './optimize/presentation.js';
export { useOptimize } from './useOptimize.js';
export function OptimizeSummary({ client, route, navigate }: { client: UsageClient; route: Route; navigate: (r: Partial<Route>) => void }) {
  const q = useOptimize(client, { action: 'list', project: route.project, sourceInstanceId: route.source, limit: 3, ruleOverrides: { agentsBytes: route.agentsBytes, descriptionCharacters: route.descriptionCharacters } });
  return <section className="panel optimize-summary"><div className="section-head"><h2>{t('optimize.summary')}</h2></div>{q.loading ? <p role="status">{t('webui.loading')}</p> : q.error ? <QueryError error={q.error} code={q.code} retry={q.retry} /> : q.data ? <><p>{t('optimize.summaryCount', { pending: q.data.pending, history: q.data.history })}</p>{q.data.suggestions.map(s => { const p = reviewPresentation(s); return <button className="config-row review-row" key={s.id} onClick={() => navigate({ page: 'optimize', optimizeView: q.data!.readView ?? undefined, decisionRevision: q.data!.decisionRevision, suggestion: s.id, suggestionRecord: s.recordId ?? undefined, optimizeCategory: undefined, optimizeGroup: 'pending', optimizeOffset: 0 })}><span className="config-identity"><strong>{p.title}</strong><span className="review-value">{p.value}</span></span><SuggestionMetric presentation={p}/></button>; })}<div className="controls"><button onClick={() => navigate({ page: 'optimize', optimizeView: q.data!.readView ?? undefined, decisionRevision: q.data!.decisionRevision, suggestion: undefined, suggestionRecord: undefined, optimizeOffset: 0, optimizeGroup: 'pending' })}>{t('optimize.viewAll')}</button><HandoffButton key={`${route.project}:${route.source}`} client={client} route={{...route,optimizeView:q.data.readView??undefined,decisionRevision:q.data.decisionRevision}} disabled={!q.data.pending}/></div><p className="note">{t('optimize.note')}</p></> : null}</section>;
}
export function OptimizeView({ client, route, navigate, pin, embedded = false }: { client: UsageClient; route: Route; navigate: (r: Partial<Route>) => void; pin: (view: string, revision: string) => void; embedded?: boolean }) {
  const request: OptimizeRequest = { action: 'list', readView: route.optimizeView, decisionRevision: route.decisionRevision, project: route.project, sourceInstanceId: route.source, group: route.optimizeGroup ?? 'pending', category: route.optimizeCategory, offset: route.optimizeOffset ?? 0, limit: 30, ruleOverrides: { agentsBytes: route.agentsBytes, descriptionCharacters: route.descriptionCharacters } };
  const q = useOptimize(client, request), navRef = useRef(pin); navRef.current = pin;
  const { busy, error, notice, run } = useReviewActions(client, route, request, q.data, navigate);
  useEffect(() => { if (q.data && !route.optimizeView) navRef.current(q.data.readView!, q.data.decisionRevision); }, [q.data, route.optimizeView]);
  const refresh = () => navigate({ optimizeView: undefined, decisionRevision: undefined, suggestion: undefined, suggestionRecord: undefined, optimizeOffset: 0 });
  const update = (patch: Partial<Route>) => navigate({ ...patch, suggestion: undefined, suggestionRecord: undefined, optimizeOffset: 0 });
  const result = q.data, selected = result?.suggestions.find(s => s.id === route.suggestion && (!route.suggestionRecord || s.recordId === route.suggestionRecord));
  const detail = selected && result && <SuggestionDetail key={selected.recordId ?? selected.id} selected={selected} result={result} client={client} route={route} busy={busy} error={error} navigate={navigate} refresh={refresh} run={run} />;
  if (embedded) return <>{q.error && <QueryError error={q.error} code={q.code} retry={refresh} />} {detail}</>;
  if (route.unassigned) return <Empty title={t('optimize.empty')} copy={t('config.emptyHint')} />;
  return <>
    <Heading title={t('optimize.title')} sub={t('optimize.note')}><div className="controls"><HandoffButton key={`${route.project}:${route.source}`} client={client} route={route} disabled={busy || q.loading || !result?.pending} /><button disabled={busy} onClick={q.loading ? q.cancel : refresh}>{t(q.loading ? 'webui.cancel' : 'config.refresh')}</button><button disabled={busy || q.loading || !result} onClick={() => void run('recheck')}>{t('optimize.recheck')}</button></div></Heading>
    {q.loading && <p role="status">{t('webui.loading')}</p>}{q.error && <QueryError error={q.error} code={q.code} retry={q.code === 'VIEW_EXPIRED' || q.code === 'NOT_FOUND' ? refresh : q.retry} />}{error && <QueryError error={error.message} code={error.code} retry={refresh} />}
    {notice && <p className="read-notice" role="status">{notice}</p>}
    {busy && <p role="status">{t('webui.loading')}</p>}
    {result && <>{result.resultStatus!=='complete'&&<p className="read-notice">{t('optimize.assessment.partial')}</p>}<details className="provenance"><summary>{t('optimize.ruleSettings')}</summary><p>{t('optimize.ruleSettingsNote')}</p><form key={`${route.agentsBytes}:${route.descriptionCharacters}`} className="controls" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); navigate({ agentsBytes: Number(data.get('agentsBytes')), descriptionCharacters: Number(data.get('descriptionCharacters')), optimizeView: undefined, decisionRevision: undefined, suggestion: undefined, suggestionRecord: undefined, optimizeOffset: 0 }); }}><label>{t('optimize.agentsBytes')}<input name="agentsBytes" type="number" min="1" max={Number.MAX_SAFE_INTEGER} step="1" required defaultValue={route.agentsBytes ?? result.ruleParameters.agentsBytesDefault} /></label><label>{t('optimize.descriptionCharacters')}<input name="descriptionCharacters" type="number" min="0" max="1024" step="1" required defaultValue={route.descriptionCharacters ?? result.ruleParameters.descriptionCharactersDefault} /></label><button disabled={busy}>{t('optimize.applyRules')}</button><button type="button" disabled={busy} onClick={() => navigate({ agentsBytes: undefined, descriptionCharacters: undefined, optimizeView: undefined, decisionRevision: undefined, suggestion: undefined, suggestionRecord: undefined, optimizeOffset: 0 })}>{t('optimize.defaultRules')}</button></form><p><code>{result.ruleParameters.version}</code></p></details><div className="config-toolbar"><nav className="config-types" aria-label={t('optimize.title')}>{(['pending', 'history'] as const).map(group => <button key={group} disabled={busy} aria-pressed={(route.optimizeGroup ?? 'pending') === group} onClick={() => update({ optimizeGroup: group })}>{t(`optimize.${group}`)} · {result[group]}</button>)}</nav><select aria-label={t('optimize.title')} value={route.optimizeCategory ?? ''} disabled={busy} onChange={e => update({ optimizeCategory: e.target.value as Route['optimizeCategory'] || undefined })}><option value="">{t('config.all')}</option>{(['repair', 'trim', 'organize', 'space'] as const).map(c => <option key={c} value={c}>{t(`optimize.${c}`)}</option>)}</select><span className="note">{timestamp(result.checkedAt, route.timezone)}</span></div>
      <section className="panel config-list review-list" aria-label={t('optimize.title')}>{result.suggestions.map(s => { const presentation = reviewPresentation(s); return <button key={s.recordId ?? s.id} className={`config-row review-row ${selected === s ? 'active' : ''}`} disabled={busy} aria-current={selected === s ? 'true' : undefined} onClick={() => navigate({ suggestion: s.id, suggestionRecord: s.recordId ?? undefined })}><span className="config-identity"><span className="config-kind">{t(`optimize.${s.category}`)}</span><strong>{presentation.title}</strong><span className="review-value">{presentation.value}</span>{route.optimizeGroup === 'history' && <span className="tag">{reviewStateLabel(s)}</span>}</span><SuggestionMetric presentation={presentation}/></button>; })}{!result.suggestions.length && <Empty title={t('optimize.empty')} copy={t(route.optimizeCategory === 'organize' ? 'optimize.organizeUnavailable' : route.optimizeCategory === 'space' ? 'optimize.spaceUnavailable' : 'optimize.emptyNote')} />}<Pagination page={result.page} onPage={optimizeOffset => navigate({ optimizeOffset, suggestion: undefined, suggestionRecord: undefined })} /></section>
      {detail}

      <details className="provenance config-coverage"><summary>{t('optimize.coverage')}</summary><p>{t('optimize.coverageNote')}</p>{result.issues.map((i, n) => <p key={n}><code>{i.code}</code>{i.path && <> · <code>{i.path}</code></>}</p>)}<p>{t('config.readVersion', { version: result.readView ?? '—' })} · {result.decisionRevision}</p></details></>}
  </>;
}
