import { useEffect,useState } from 'react';
import type { UsageClient,PricingResult } from '@wombat/client';
import { t } from '@wombat/client/locale';
import { Heading,safeURL } from './components.js';
export function PricesView({client}:{client:UsageClient}){
 const [result,setResult]=useState<PricingResult>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[action,setAction]=useState<'status'|'update'>('status'),[revision,setRevision]=useState(0),[tier,setTier]=useState('standard');
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');void client.prices({action},{signal:abort.signal}).then(r=>{if(!abort.signal.aborted)setResult(r);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[client,action,revision]);
 return <><Heading title={t('webui.prices')} sub={result?`${result.catalog.revision} · ${result.catalog.verifiedAt}`:undefined}><select aria-label={t('webui.priceTier')} value={tier} onChange={e=>setTier(e.target.value)}>{(['standard','longContext'] as const).map(v=><option value={v} key={v}>{t(`webui.${v}`)}</option>)}</select></Heading><div className="cost-note"><span>{t('webui.priceDescription')}</span></div><p className="table-scroll-hint">{t('webui.scrollPrices')}</p>{loading&&<p role="status">{t('webui.loading')}</p>}{error&&<div className="warning-box" role="alert"><p>{t('webui.priceStale')}</p><p>{error}</p><button onClick={()=>setRevision(n=>n+1)}>{t('webui.retry')}</button></div>}{result&&<><section className="panel"><div className="report-table-wrap" tabIndex={0} aria-label={t('webui.prices')}><table className="project-table price-table"><thead><tr><th>{t('webui.model')} / {t('webui.basis')}</th><th>{t('webui.uncached')}</th><th>{t('webui.cacheRead')}</th><th>{t('webui.cacheCreate')}</th><th>{t('webui.output')}</th></tr></thead><tbody>{result.catalog.models.map(m=>{const rates=tier==='standard'?m.rates:m.longContext?.rates;return <tr key={m.id}><td><details><summary>{m.id}</summary><p className="subtle">{m.aliases.join(' / ')}<br/>{m.longContext?t('webui.longThreshold',{tokens:m.longContext.inputAbove.toLocaleString()}):t('webui.noLongTier')}</p>{safeURL(m.source)&&<a target="_blank" rel="noreferrer" href={m.source}>{t('webui.official')}</a>}</details></td>{(['input','cacheRead','cacheCreate','output'] as const).map(k=><td key={k}>{!rates?'—':rates[k]==null?t('webui.notListed'):'$'+rates[k]}</td>)}</tr>;})}</tbody></table></div></section><div className="section-head"><h2>{t('webui.priceSource')}</h2><button disabled={loading} onClick={()=>{setAction('update');setRevision(n=>n+1);}}>{t('webui.priceUpdate')}</button></div><p className="subtle">{t('webui.catalogBoundary')}</p><p className="note">{result.origin} · {result.updated?t('webui.priceUpdated'):t('webui.priceCurrent')}</p></>}</>;
}
