import {useState} from 'react';
import type {UsageClient,UsageResult,UsageScope} from '@wombat/client';
import {locale,t,inspectionCandidateText,inspectionActivityText,inspectionActivityFindingText,inspectionActivityPolicyText,inspectionOpportunityCheckText,inspectionOpportunityFindingText,inspectionOpportunityPolicyText} from '@wombat/client/locale';
import {Pagination,Pair,timestamp} from './components.js';
import {QueryError} from './Feedback.js';
import {fromScope,scopeOf,type Route} from './state.js';
import {useUsageQuery} from './useUsageQuery.js';
type Inspection=NonNullable<UsageResult['inspection']>;
type Proof=Inspection['trajectory'][number]['evidence'];
export function inspectionRoute(e:Proof):Partial<Route>{
 return {...fromScope(e.scope),page:'threads',snapshot:e.snapshotId,thread:e.threadId,turn:e.turnId??(e.operationId?'unassigned':undefined),turnView:'all',operation:e.operationId??undefined,turnOffset:0,offset:0,search:undefined};
}
function ProofLinks({proofs,navigate}:{proofs:Proof[];navigate:(r:Partial<Route>)=>void}){
 return <div className="inspection-proof">{proofs.map((e,i)=><button key={JSON.stringify([e.threadId,e.turnId,e.operationId])} className="link" onClick={()=>navigate(inspectionRoute(e))}>{t('inspection.evidence')}{proofs.length>1?` ${i+1}`:''}</button>)}</div>;
}
function Candidate({row,navigate}:{row:Inspection['candidates'][number];navigate:(r:Partial<Route>)=>void}){
 return <article className="inspection-card"><h4>{row.title??row.threadId}</h4><Pair summary={row.usage}/>{inspectionCandidateText(row).map(finding=><div key={finding.title}><strong>{finding.title}</strong><p>{finding.observed}</p><p>{finding.advice}</p></div>)}<ProofLinks proofs={row.evidence} navigate={navigate}/></article>;
}
export function UsageInspection({client,snapshotId,route,navigate,refresh,threadId}:{client:UsageClient;snapshotId:string;route:Route;navigate:(r:Partial<Route>)=>void;refresh:()=>void;threadId?:string}){
 const [open,setOpen]=useState(false);
 return <details className="panel inspection" onToggle={e=>setOpen(e.currentTarget.open)}><summary>{t(threadId?'inspection.trajectory':'inspection.title')}</summary>{open&&<InspectionQuery key={JSON.stringify([snapshotId,scopeOf(route),threadId])} client={client} snapshotId={snapshotId} scope={scopeOf(route)} timezone={route.timezone} navigate={navigate} refresh={refresh} threadId={threadId}/>}</details>;
}
function InspectionQuery({client,snapshotId,scope,timezone,navigate,refresh,threadId}:{client:UsageClient;snapshotId:string;scope:UsageScope;timezone:string;navigate:(r:Partial<Route>)=>void;refresh:()=>void;threadId?:string}){
 const [kind,setKind]=useState<'investigate'|'resources'|'review'|'context'>('investigate'),[offset,setOffset]=useState(0);
 const action=threadId?'trajectory':kind;
 const reviewScope=scope.allTime||scope.undated?{...scope,allTime:undefined,undated:undefined,since:undefined,until:undefined}:scope;
 const {result,error,errorCode,expired,loading,retry}=useUsageQuery(client,{action,snapshotId,scope:action==='review'?reviewScope:scope,...(threadId?{threadId}:{}),...(action==='review'?{}:{offset,limit:10})});
 const i=result?.inspection,p=i?.policy;
 return <>{!threadId&&<div className="controls"><select aria-label={t('inspection.title')} value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setOffset(0);}}>{(['investigate','resources','review','context'] as const).map(k=><option key={k} value={k}>{t(`inspection.${k}`)}</option>)}</select></div>}<p>{t('inspection.note')}</p>{loading&&<p role="status">{t('webui.loading')}</p>}{error&&<QueryError error={error} code={errorCode} retry={expired?refresh:retry}/>}{i&&<><div className="note">{i.limitations.map(l=><p key={l}>{t(`inspection.limit.${l}`)}</p>)}</div>{p&&<details><summary>{t('inspection.policy')}</summary><p>{t('inspection.policyText',{tokens:p.minimumTokens,input:p.minimumInput,cache:p.maximumCacheShare*100,jump:p.minimumInputJump,operations:p.minimumDeterminateOperations,failures:p.minimumFailures,share:p.minimumFailureShare*100,repeats:p.minimumRepeatedRequests})}</p></details>}
 {i.activity&&<><h4>{t('inspection.activity.title')}</h4><details><summary>{t('inspection.policy')}</summary><p>{inspectionActivityPolicyText(i.activity.policy)}</p></details>{inspectionActivityText(i.activity).map(line=><p className="note" key={line}>{line}</p>)}{i.activity.findings.map(f=><article className="inspection-card" key={f.id}><h4>{f.tool}</h4><p className="note">{f.project??t('webui.unknown')}</p>{inspectionActivityFindingText(f).map(signal=><div key={signal.title}><strong>{signal.title}</strong><p>{signal.observed}</p><p>{signal.advice}</p></div>)}<p>{t('inspection.activity.currentEvidence')}</p><ProofLinks proofs={f.evidence} navigate={navigate}/>{f.baselineEvidence.length>0&&<><p>{t('inspection.activity.baselineEvidence')}</p><ProofLinks proofs={f.baselineEvidence} navigate={navigate}/></>}</article>)}</>}
 {i.opportunities&&<><h4>{t('inspection.opportunities.title')}</h4><p className="note">{t('inspection.opportunities.note')}</p>{i.opportunities.checks.filter(c=>c.findingCount>0).map(check=>{const c=inspectionOpportunityCheckText(check);return <section key={check.rule}><h4>{c.title}</h4><p>{t('inspection.opportunities.count',{shown:check.findings.length,total:check.findingCount})}</p>{c.gaps.map(g=><p className="note" key={g}>{g}</p>)}{check.findings.map(f=><article className="inspection-card" key={f.id}>{f.object&&<h4><code>{f.object}</code></h4>}{inspectionOpportunityFindingText(f).map(line=><p key={line}>{line}</p>)}<p>{c.advice}</p><ProofLinks proofs={f.evidence} navigate={navigate}/>{f.baselineEvidence.length>0&&<><p>{t('inspection.activity.baselineEvidence')}</p><ProofLinks proofs={f.baselineEvidence} navigate={navigate}/></>}</article>)}</section>;})}<details><summary>{t('inspection.opportunities.all')}</summary>{i.opportunities.checks.map(check=>{const c=inspectionOpportunityCheckText(check);return <p key={check.rule}>{c.title} · {c.status}{c.gaps.length>0?' · '+c.gaps.join(' · '):''}</p>;})}</details><details><summary>{t('inspection.policy')}</summary>{inspectionOpportunityPolicyText(i.opportunities.policy).map(line=><p key={line}>{line}</p>)}</details></>}
 {i.kind==='investigate' &&!i.candidateCount&&!i.activity?.findingCount&&!i.opportunities?.checks.some(c=>c.findingCount)&&<p>{t('inspection.noCandidates')}</p>}{i.candidates.map(c=><Candidate key={c.threadId} row={c} navigate={navigate}/>)}
 {i.trajectory.map(point=><article className="inspection-card" key={point.measurementId}><h4>{point.timestamp?timestamp(point.timestamp,timezone):t('webui.unknown')}</h4><p>{t('inspection.input')}: {point.input?.toLocaleString()??'—'} Token · {t('inspection.uncachedDelta')}: {point.uncachedDelta??'—'} Token</p>{point.boundary&&<p className="note">{t(`inspection.boundary.${point.boundary}`)}</p>}{point.compactionComparison&&<><p>{t('inspection.compactionComparison',{before:point.compactionComparison.beforeInput,after:point.compactionComparison.afterInput,difference:point.compactionComparison.inputDifference})}</p><p className="note">{t('inspection.compactionNote')}</p><ProofLinks proofs={[point.compactionComparison.beforeEvidence]} navigate={navigate}/></>}<ProofLinks proofs={[point.evidence]} navigate={navigate}/></article>)}
 {i.context&&<><p>{t('inspection.contextCount',{count:i.context.injectedRecords,windows:i.context.modelWindowRecords})}</p>{i.context.records.length===0&&<p>{t('common.no_records')}</p>}{i.context.records.map(record=><article className="inspection-card" key={record.id}><h4>{t(`inspection.contextKind.${record.kind}`)}</h4><p>{record.timestamp?timestamp(record.timestamp,timezone):t('webui.unknown')}</p>{record.modelContextWindow!=null?<p>{record.model??t('webui.unknown')} · {t('inspection.modelWindow',{tokens:record.modelContextWindow})}</p>:<p>{t('inspection.contentUnknown')}</p>}<ProofLinks proofs={[record.evidence]} navigate={navigate}/></article>)}</>}
 {i.resources.map(resource=><article className="inspection-card" key={resource.id}><h4><code>{resource.path}</code></h4><p className="note">{resource.project??t('webui.unknown')} · {t('inspection.identity')}: {resource.identityBasis==='reported_path'?t('inspection.reported_path'):resource.identityBasis==='lexical_windows'?t('inspection.lexical_windows'):t('inspection.lexical_posix')}</p><p>{t('inspection.reads')}: {resource.reads} · {t('inspection.proposed')}: {resource.proposedChanges} · {t('inspection.reported')}: {resource.reportedChanges}</p><p>{t('inspection.duration')}: {resource.knownDurationMs??'—'} ms · {t('inspection.coveredDuration',{count:resource.durationCoveredOperations})}</p><ProofLinks proofs={resource.evidence} navigate={navigate}/></article>)}
 {i.review&&<><h4>{t('inspection.review')} · {result!.scope.since} — {result!.scope.until}</h4>{i.review.comparison?.kind==='periods'&&<><p>{t('comparison.baseline')}: <Pair summary={i.review.comparison.baseline.usage}/></p><p>{t('comparison.current')}: <Pair summary={i.review.comparison.current.usage}/></p><p>{t('comparison.delta')}: {i.review.comparison.delta.tokens??'—'} Token</p>{(i.review.comparison.current.partial||i.review.comparison.baseline.partial)&&<p className="note">{t('comparison.partial')}</p>}</>}{i.review.concentration&&<><h4>{t('inspection.concentration')}</h4><p>{t('inspection.concentrationShares',{top:i.review.concentration.topTaskShare==null?'—':new Intl.NumberFormat(locale.getSnapshot().locale,{style:'percent',maximumFractionDigits:1}).format(i.review.concentration.topTaskShare),five:i.review.concentration.topFiveShare==null?'—':new Intl.NumberFormat(locale.getSnapshot().locale,{style:'percent',maximumFractionDigits:1}).format(i.review.concentration.topFiveShare),ten:i.review.concentration.topTenShare==null?'—':new Intl.NumberFormat(locale.getSnapshot().locale,{style:'percent',maximumFractionDigits:1}).format(i.review.concentration.topTenShare)})}</p><p>{t('inspection.remainingTasks')}: <Pair summary={i.review.concentration.remainingTaskUsage}/></p></>}<h4>{t('inspection.topTasks')}</h4>{i.review.topTasks.map(c=><Candidate row={c} key={c.threadId} navigate={navigate}/>)}<h4>{t('webui.models')}</h4>{i.review.models.map(m=><p key={m.key??''}>{m.key??t('webui.unknown')} · <Pair summary={m.usage}/></p>)}<h4>{t('inspection.tools')}</h4>{i.review.tools.map(tool=><p key={tool.kind}>{tool.kind} · {tool.operations}</p>)}</>}
 {i.kind!=='review'&&<Pagination page={result!.page} onPage={setOffset}/>}</>}</>;
}
