import { useState } from 'react';
import type { UsageClient, UsageScope, UsageSummary } from '@wombat/client';
import { t, monthLabel, pricingIssueText } from '@wombat/client/locale';
import { Composition, Modal, Pair, Pagination, Token, amount, currency, directoryName } from './components.js';
import { QueryError } from './Feedback.js';
import { useUsageQuery } from './useUsageQuery.js';
import { fromScope, shiftDate, linkedReturn, type Route } from './state.js';
export interface UsageSelection {summary:UsageSummary;scope:UsageScope;snapshotId:string}
export function CostComposition({summary}:{summary:UsageSummary}){return <div className="report-table-wrap"><table className="project-table cost-composition"><caption>{t('webui.costComposition')}</caption><thead><tr><th>{t('webui.type')}</th><th className="num">Token</th><th className="num">USD</th></tr></thead><tbody>{summary.price.components.map((c,i)=><tr key={i}><td>{['input','output','cacheRead','cacheCreate'].includes(c.category)?categoryLabel(c.category):c.category}</td><td className="num"><Token value={c.tokens}/></td><td className="num">{c.status==='unknown'?t('webui.amountUnknown'):c.cost==null?currency(Number(c.knownCost))+'*':currency(Number(c.cost))}</td></tr>)}</tbody></table></div>;}
export function UsageDrawer({client,selection,route,navigate,onClose}:{client:UsageClient;selection:UsageSelection;route:Route;navigate:(r:Partial<Route>)=>void;onClose:()=>void}){
 const {summary,scope,snapshotId}=selection,[dimension,setDimension]=useState<'time'|'models'|'projects'|'threads'>('threads'),[offset,setOffset]=useState(0);
 const q=useUsageQuery(client,{action:dimension==='threads'?'threads':'usage',snapshotId,scope,group:dimension==='threads'?undefined:route.group,presentation:dimension==='time'?'distribution':dimension==='threads'?undefined:dimension,sort:dimension==='threads'?'recent':'tokens',offset,limit:12});
 const go=(patch:Partial<Route>)=>{onClose();navigate({...fromScope(scope),returnTo:linkedReturn(route),page:'threads',snapshot:snapshotId,offset:0,thread:undefined,turn:undefined,...patch});};
 return <Modal title={t('webui.usageDetail')} onClose={onClose} drawer><div className="drawer-total"><Pair summary={summary}/></div><p className="note">{[scope.undated?t('webui.undated'):scope.allTime?t('webui.allDates'):scope.since??t('webui.allDates'),scope.until?shiftDate(scope.until,-1):undefined,scope.timezone??route.timezone].filter(Boolean).join(' · ')}</p><Composition summary={summary}/><CostComposition summary={summary}/><p className="note">{t('webui.costNote')}</p><nav className="config-types drawer-tabs" aria-label={t('webui.usageDetail')}>{(['time','models','projects','threads'] as const).map(d=><button key={d} aria-pressed={dimension===d} onClick={()=>{setDimension(d);setOffset(0);}}>{t(d==='time'?'webui.trend':d==='threads'?'webui.relatedTasks':`webui.${d}`)}</button>)}</nav>
 {q.loading&&<p role="status">{t('webui.loading')}</p>}{q.error&&<QueryError error={q.error} code={q.errorCode} retry={q.retry}/>}{q.result?.items.map((i,n)=>i.kind==='usage'?<button className="drawer-row" key={n} onClick={()=>go(fromScope(i.scope))}><span title={i.scope.project??''}>{dimension==='projects'?directoryName(i.scope.project):dimension==='models'?i.model??t('webui.unknown'):i.date?(route.group==='month'?monthLabel(i.date):i.date):t('webui.undated')}</span><Pair summary={i.usage}/></button>:i.kind==='thread'?<button className="drawer-row" key={i.id} onClick={()=>go({thread:i.id})}><span>{i.title??i.upstreamId??i.id}</span><Pair summary={i.matchedUsage}/></button>:null)}{q.result&&<Pagination page={q.result.page} onPage={setOffset}/>}
 <details className="provenance"><summary>{t('webui.basis')}</summary><p>{amount(summary)} · {summary.price.priceRevision}</p><ul>{summary.price.issues.map((issue,index)=><li key={index}>{pricingIssueText(issue)} <code>({issue})</code></li>)}</ul><p>{snapshotId}</p></details></Modal>;
}
function categoryLabel(category:string){switch(category){case 'input':return t('webui.nonCacheInput');case 'output':return t('webui.output');case 'cacheRead':return t('webui.cacheRead');case 'cacheCreate':return t('webui.cacheCreate');default:return category;}}
