import {syntheticUseBasis} from './use-basis.js';
import {CoreError,type ConfigItem,type ConfigRequest,type ConfigResult,type QueryOptions} from '@wombat/client';
import {inventory,configFixture} from './configuration.js';
const project='/synthetic/wombat',other='/synthetic/reporter',at='2026-10-04T02:00:00Z';
function objects():ConfigItem[]{
 const rows=structuredClone(inventory);rows.forEach(item=>{item.characters=item.bytes;item.bytesSource='synthetic fixture';item.estimate={tokens:item.contentTokens!,encoding:'synthetic',method:'synthetic-full-content-v1',payload:'fullContent',contentHash:item.contentHash,applicability:'referenceEncodingOnly',tokenizerVersion:'v1'};item.sourceContexts=[{inventoryId:item.id,global:false,sourceInstanceId:item.sourceInstanceId,contentHash:item.contentHash,configuredState:item.configuredState,counts:structuredClone(item.counts),observation:item.observation,lastRecordAt:at}];});
 rows[0].observation='loaded_only';rows[0].counts.fileReads=1;rows[0].sourceContexts[0].observation='loaded_only';rows[0].sourceContexts[0].counts.fileReads=1;
 rows[1].skillMetadata={status:'parsed',descriptionCharacters:100,issues:[],diagnostics:[]};rows[3].nativeKey='synthetic-hook';rows[3].usageCount=null;rows[3].observation='unknown';rows[3].counts={fileReads:0,toolCalls:0,resourceReads:0,succeeded:0,failed:0,outcomeUnknown:0};
 rows.push({...structuredClone(rows[1]),id:'preview-invalid-skill',contentHash:'synthetic-invalid-skill',estimate:{...rows[1].estimate!,contentHash:'synthetic-invalid-skill'},name:'synthetic-invalid-format',path:project+'/skills/invalid/SKILL.md',observation:'unknown',usageCount:null,counts:{fileReads:0,toolCalls:0,resourceReads:0,succeeded:0,failed:0,outcomeUnknown:0},skillMetadata:{status:'invalid',descriptionCharacters:null,issues:['nameTypeInvalid'],diagnostics:[{code:'nameTypeInvalid',field:'name',line:2,column:7,current:'array',expected:'string'}]},bodyEstimateStatus:'invalid',bodyTokenEstimate:null});
 rows.push({...structuredClone(rows[0]),id:'preview-historical-rule',name:'Historical instructions',path:other+'/AGENTS.md',project:other,authorizedProjects:[other],current:false,stale:true,bytes:null,contentTokens:null,characters:null,estimate:null,estimateStatus:'unavailable',measurementStatus:'missing',configuredState:'missing',contentHash:'synthetic-historical',observation:'loaded_only'});
 rows.push({...structuredClone(rows[2]),id:'preview-unreadable-mcp',name:'synthetic-unreadable',path:other+'/config.toml',project:other,authorizedProjects:[other],configuredState:'unreadable',bytes:null,contentTokens:null,characters:null,estimate:null,estimateStatus:'unavailable',measurementStatus:'unreadable',observation:'unknown',usageCount:null,counts:{fileReads:0,toolCalls:0,resourceReads:0,succeeded:0,failed:0,outcomeUnknown:0}});
 rows[0].authorizedProjects=[project,other];rows[0].sourceContexts.push({...structuredClone(rows[0].sourceContexts[0]),inventoryId:'preview-rule-secondary',global:true,sourceInstanceId:'preview-secondary',observation:'unknown',counts:{fileReads:0,toolCalls:0,resourceReads:0,succeeded:0,failed:0,outcomeUnknown:0}});
 rows.slice(4).forEach(item=>item.sourceContexts=[{inventoryId:item.id,global:false,sourceInstanceId:item.sourceInstanceId,contentHash:item.contentHash,configuredState:item.configuredState,counts:structuredClone(item.counts),observation:item.observation,lastRecordAt:item.lastRecordAt}]);
 return rows;
}
export function inventoryFixture(request:ConfigRequest):ConfigResult{
 if(request.readView&&request.readView!=='preview-config')throw new CoreError('VIEW_EXPIRED','Synthetic configuration view expired');
 const scoped=objects().filter(item=>(!request.scope?.project||item.authorizedProjects.includes(request.scope.project))&&(!request.scope?.sourceInstanceId||item.sourceContexts.some(context=>context.sourceInstanceId===request.scope!.sourceInstanceId))&&(!request.scope?.agentKind||request.scope.agentKind==='codex'));
 const since=request.scope?.since,until=request.scope?.until;
 scoped.forEach(item=>{if(request.scope?.sourceInstanceId==='preview-secondary'||request.scope?.threadId&&request.scope.threadId!==(item.project===other?'preview-task-1':'preview-task')||request.scope?.project&&item.project!==request.scope.project||since&&at<since||until&&at>=until){item.observation='unknown';item.usageCount=null;item.lastRecordAt=null;item.relatedTasks=0;item.relatedTurns=0;item.counts={fileReads:0,toolCalls:0,resourceReads:0,succeeded:0,failed:0,outcomeUnknown:0};item.sourceContexts.forEach(context=>{context.counts=structuredClone(item.counts);context.observation='unknown';context.lastRecordAt=null;});}});
 scoped.forEach(item=>{item.useBasis=item.kind==='hook'?null:syntheticUseBasis(item.kind==='rule'?'rule_load_or_read':'object_use',item.kind!=='rule'&&item.usageCount==null?'unknown':'observed',request.scope);if(item.useBasis&&!request.scope?.sourceInstanceId)item.useBasis.scope.sourceInstanceIds=[...new Set(item.sourceContexts.map(context=>context.sourceInstanceId))];});
 const rows=scoped.filter(item=>(!request.itemId||item.id===request.itemId)&&(!request.kind||item.kind===request.kind)&&(!request.kinds||request.kinds.includes(item.kind))&&(!request.observation||item.observation===request.observation)&&(!request.search||`${item.name} ${item.path}`.toLowerCase().includes(request.search.toLowerCase())));
 rows.sort((a,b)=>request.sort==='size'?(b.bytes??-1)-(a.bytes??-1):request.sort==='name'?a.name.localeCompare(b.name):(b.contentTokens??-1)-(a.contentTokens??-1));
 if(request.itemId&&!rows.length)throw new CoreError('NOT_FOUND','Synthetic configuration object not found in this scope');
 const result=configFixture({}),offset=request.offset??0,limit=request.limit??30;
 const evidence:ConfigResult['evidence']=request.action==='evidence'?rows.filter(item=>item.observation!=='unknown'&&item.kind!=='hook').flatMap(item=>Array.from({length:item.kind==='rule'?item.counts.fileReads:item.usageCount??0},(_,index)=>({id:`${item.id}-record-${index}`,sourceInstanceId:item.sourceInstanceId,itemId:item.id,threadId:item.project===other?'preview-task-1':'preview-task',turnId:item.project===other?'preview-task-1-turn-1':'preview-turn',title:'Synthetic configuration evidence',project:item.project,timestamp:at,eventType:item.kind==='mcp'?'tool_call':item.kind==='rule'?'instruction_load':'file_read',outcome:index===1?'failed':'completed',association:'exact'}))):[];
 const related:ConfigResult['relatedScopes']=request.action==='related_scopes'?rows.flatMap(item=>item.authorizedProjects.map(project=>({project,evidenceCount:item.usageCount??0}))):[];
 const pageRows=request.action==='evidence'?evidence:request.action==='related_scopes'?related:rows;
 return {...result,action:request.action??'list',scope:request.scope??{},authorizedProjects:[project,other],authorizedSourceRoots:['/synthetic/codex-home'],summary:{currentItems:scoped.filter(item=>item.current).length,historicalItems:scoped.filter(item=>!item.current).length,observedItems:scoped.filter(item=>item.observation!=='unknown').length},items:request.action==='list'||!request.action?rows.slice(offset,offset+limit):rows,evidence:evidence.slice(offset,offset+limit),relatedScopes:related.slice(offset,offset+limit),page:{offset,limit,total:pageRows.length,nextOffset:offset+limit<pageRows.length?offset+limit:null},coverage:{status:'partial',historyStatus:'partial',issues:[{code:'configUnreadable',path:other+'/config.toml'},{code:'historyCoverageUnknown'}],supportedEvidence:['file_read','instruction_load','tool_call','resource_read'],absenceObservable:false},hookRegistry:{status:'partial',nativeVersion:'synthetic-native-v1',checkedAt:at,contexts:[{project,complete:true,registrations:[{itemId:'preview-hook',nativeKey:'synthetic-hook',contentHash:'synthetic-hook',registrationHash:'synthetic-registration',enabled:true,trust:'trusted',handler:'command',source:'synthetic-native-registry'}]},{project:other,complete:false,registrations:[{itemId:'preview-hook',nativeKey:'synthetic-hook-other',contentHash:'synthetic-hook',registrationHash:'synthetic-other-registration',enabled:false,trust:'untrusted',handler:'command',source:'synthetic-native-registry'}]}]}};
}
export function previewInventory(scenario:string){return async(request:ConfigRequest,options?:QueryOptions)=>{if(options?.signal?.aborted)throw new CoreError('CANCELLED','Cancelled');if(scenario==='config-detail-failed'&&request.action!=='list')throw new CoreError('SOURCE_UNREADABLE','Synthetic configuration detail unavailable');return inventoryFixture(request);};}
