import {CoreError,type UsageRequest,type UsageResult,type UsageSummary,type QueryOptions} from '@wombat/client';
import {t} from '@wombat/client/locale';
const checked='2026-10-04T02:00:00Z',source='preview';
const price=(measurements:number)=>{const micros=measurements*1000;return `${Math.floor(micros/1000000)}.${String(micros%1000000).padStart(6,'0')}`;};
const summary=(measurements:number):UsageSummary=>({measurementCount:measurements,inputTotal:1000*measurements,cacheHitRate:measurements?0.2:null,unpricedTokens:0,tokens:{input:800*measurements,cacheRead:200*measurements,cacheCreate:0,output:100*measurements,reasoning:30*measurements,total:1100*measurements},price:{currency:'USD',policy:'synthetic',priceRevision:'preview',knownCost:price(measurements),cost:price(measurements),status:'priced',components:[],basis:[],issues:[]}});
const threads=Array.from({length:43},(_,index)=>({id:index===0?'preview-task':`preview-task-${index}`,index,project:index%2?'/synthetic/reporter':'/synthetic/wombat',model:index%3===0?null:index%2?'synthetic-small':'synthetic-model',effort:index%3===0?null:index%2?'low':'medium',at:index===42?null:`2026-10-0${index%4+1}T02:00:00Z`,measurements:index===41?0:2}));
function matches(row:typeof threads[number],request:UsageRequest){
 const scope=request.scope??{},time=row.at;
 return (!scope.sourceInstanceId||scope.sourceInstanceId===source)&&(!scope.agentKind||scope.agentKind==='codex')&&(!scope.project||scope.project===row.project)&&!scope.projectUnknown&&(!scope.model||scope.model===row.model)&&(!scope.modelUnknown||row.model===null)&&(!scope.reasoningEffort||scope.reasoningEffort===row.effort)&&(!scope.effortUnknown||row.effort===null)&&(!scope.threadId||scope.threadId===row.id)&&(!scope.undated||time===null)&&(scope.allTime||scope.undated||!!time&&(!scope.since||time>=scope.since)&&(!scope.until||time<scope.until))&&(!request.search||`${t('preview.task')} ${row.index+1} ${row.id} ${row.project}`.toLowerCase().includes(request.search.toLowerCase()));
}
/** A bounded synthetic truth set answers real typed list/detail requests, including pages. */
export function taskFixture(request:UsageRequest,scenario:string):UsageResult{
 if(request.snapshotId&&request.snapshotId!=='preview:1'&&request.snapshotId!=='live:preview-initial')throw new CoreError('VIEW_EXPIRED','Synthetic task view expired');
 const scoped=scenario==='empty'?[]:threads.filter(row=>matches(row,request));
 const rows=[...scoped].sort((a,b)=>request.sort==='recent'||request.sort==='time'?(b.at??'').localeCompare(a.at??'')||a.index-b.index:b.measurements-a.measurements||a.index-b.index);
 const target=threads.find(row=>row.id===request.threadId),measures=scoped.reduce((n,row)=>n+row.measurements,0);
 if(request.action==='steps'&&(!target||!request.turnId||![`${target.id}-turn-0`,target.id==='preview-task'?'preview-turn':`${target.id}-turn-1`,`${target.id}-turn-2`].includes(request.turnId)))throw new CoreError('NOT_FOUND','Synthetic turn not found');
 let items:UsageResult['items'];
 if(request.action==='threads')items=rows.map(row=>({kind:'thread',id:row.id,upstreamId:`synthetic-upstream-${row.index}`,agentKind:'codex',sourceInstanceId:source,title:`${t('preview.task')} ${row.index+1}`,project:row.project,startedAt:row.at,lastActivityAt:row.at,matchedLastActivityAt:row.at,matchedTurnCount:row.measurements?2:null,models:row.model?[row.model]:[],reasoningEfforts:row.effort?[row.effort]:[],threadUsage:summary(row.measurements),matchedUsage:summary(row.measurements)}));
 else if(request.action==='turns')items=target?Array.from({length:3},(_,index)=>({kind:'turn' as const,id:target.id==='preview-task'&&index===1?'preview-turn':`${target.id}-turn-${index}`,threadId:target.id,ordinal:index+1,startedAt:target.at,endedAt:scenario==='running'&&index===2?null:target.at,lastActivityAt:target.at,status:scenario==='running'&&index===2?'running':index===0?'unknown':'completed',models:target.model?[target.model]:[],reasoningEfforts:target.effort?[target.effort]:[],usage:summary(index&&target.measurements?1:0),matchedUsage:summary(index&&target.measurements&&matches(target,request)?1:0)})).filter(row=>!request.matchedOnly||row.matchedUsage.measurementCount>0):[];
 else if(request.action==='steps')items=target&&target.measurements&&request.turnId&&[target.id==='preview-task'?'preview-turn':`${target.id}-turn-1`,`${target.id}-turn-2`].includes(request.turnId)?[{kind:'measurement',id:`${request.turnId}-measurement`,threadId:target.id,turnId:request.turnId,timestamp:target.at,model:target.model,reasoningEffort:target.effort,usage:summary(target.measurements?1:0),sequence:1,timePrecision:target.at?'second':'unknown',matchesScope:matches(target,request)}]:[];
 else {
  const groups=new Map<string,typeof rows>();
  for(const row of rows){const key=request.presentation==='details'?`${row.model??''}\0${row.effort??''}`:request.presentation==='models'?row.model??'':request.presentation==='projects'?row.project:row.at?(request.group==='month'?'2026-10-01':request.group==='week'?'2026-09-28':row.at.slice(0,10)):'';const group=groups.get(key)??[];group.push(row);groups.set(key,group);}
  items=[...groups].map(([key,group])=>({kind:'usage' as const,isSubtotal:!['models','projects','details'].includes(request.presentation??''),share:measures?group.reduce((n,row)=>n+row.measurements,0)/measures:null,costShare:measures?group.reduce((n,row)=>n+row.measurements,0)/measures:null,model:request.presentation==='models'?key||null:request.presentation==='details'?key.split('\0')[0]||null:undefined,reasoningEffort:request.presentation==='details'?key.split('\0')[1]||null:undefined,date:!['models','projects','details'].includes(request.presentation??'')?key||null:undefined,endDate:!['models','projects','details'].includes(request.presentation??'')&&key?(request.group==='month'?'2026-10-31':request.group==='week'?'2026-10-04':key):null,usage:summary(group.reduce((n,row)=>n+row.measurements,0)),scope:{...request.scope,...(request.presentation==='projects'?{project:key}:request.presentation==='models'?{model:key||undefined,modelUnknown:!key}:request.presentation==='details'?{model:key.split('\0')[0]||undefined,modelUnknown:!key.split('\0')[0],reasoningEffort:key.split('\0')[1]||undefined,effortUnknown:!key.split('\0')[1]}:key?{since:key,until:request.group==='month'?'2026-11-01':request.group==='week'?'2026-10-05':new Date(Date.parse(key)+86400000).toISOString().slice(0,10)}:{undated:true})}}));
 }
 if(request.action==='usage'||request.action==='refresh')items.sort((a,b)=>a.kind==='usage'&&b.kind==='usage'?(request.sort==='time'?(a.date??'').localeCompare(b.date??''):(b.usage.tokens.total??0)-(a.usage.tokens.total??0)):0);
 const buckets=items.filter((item):item is Extract<UsageResult['items'][number],{kind:'usage'}>=>item.kind==='usage'&&item.date!=null);const max=Math.max(0,...buckets.map(item=>item.usage.tokens.total??0)),peak=buckets.filter(item=>item.usage.tokens.total===max);
 const limit=request.limit??20,located=request.locateThreadId??request.locateTurnId,position=located?items.findIndex(row=>'id' in row&&row.id===located):-1,offset=position>=0?Math.floor(position/limit)*limit:request.offset??0;
 const filteredCount=request.action==='steps'?target&&matches(target,request)?items.length:0:request.action==='turns'?target&&matches(target,request)?target.measurements:0:measures;
 return {outputVersion:3,action:request.action??'usage',snapshotRef:{snapshotId:request.snapshotId??'preview:1',createdAt:checked},scope:request.scope??{},distribution:{maxTokens:max,maxCost:price(max/1100),unpricedTokens:0,peakTokenDates:peak.map(item=>item.date??null),peakCostDates:peak.map(item=>item.date??null),peakTokenScopes:peak.map(item=>item.scope),peakCostScopes:peak.map(item=>item.scope)},availableRange:{since:'2026-10-01',until:'2026-10-05'},summary:summary(filteredCount),items:items.slice(offset,offset+limit),page:{offset,limit,total:items.length,nextOffset:offset+limit<items.length?offset+limit:null},quality:{status:scenario==='partial'?'partial':'complete',issues:[],sources:[{source:{id:source,agentKind:'codex',root:'/synthetic/codex-home'},adapterVersion:'synthetic-v1',sourceVersions:['synthetic'],capabilities:{usage:true,threads:true,turns:true,operations:false,reasoningEffort:true,responseIdentity:true,measurementGrain:['request']},status:scenario==='partial'?'partial':'complete',filesRead:1,bytesRead:1,issues:[]}]},facets:{directories:['/synthetic/wombat','/synthetic/reporter'],hasUnassigned:false,models:['synthetic-model','synthetic-small'],reasoningEfforts:['low','medium'],agents:['codex'],discoveredThreadCount:scenario==='empty'?0:threads.length}};
}
export function previewTasks(scenario:string){
 let observations=0;
 return async(request:UsageRequest,options?:QueryOptions):Promise<UsageResult>=>{
  if(options?.signal?.aborted)throw new CoreError('CANCELLED','Cancelled');
  if(request.action==='usage'&&!request.snapshotId)observations++;
  if(scenario==='tasks-refresh-failed'&&observations>1)throw new CoreError('SOURCE_UNREADABLE','Synthetic refresh failed');
  if(scenario==='tasks-delayed'){await new Promise<void>((resolve,reject)=>{const timer=setTimeout(resolve,request.scope?.project==='/synthetic/wombat'?80:10);options?.signal?.addEventListener('abort',()=>{clearTimeout(timer);reject(new CoreError('CANCELLED','Cancelled'));},{once:true});});}
  if(options?.signal?.aborted)throw new CoreError('CANCELLED','Cancelled');return taskFixture(request,scenario);
 };
}
