import { t } from '@wombat/client/locale';
import { useState } from 'react';
import { shiftDate, today, type Route } from '../state.js';
import type { WorkspaceData } from '../useWorkspace.js';
export function Filters({ kind, route, data, apply }: { kind: 'dates' | 'filters'; route: Route; data?: WorkspaceData; apply: (r: Partial<Route>) => void }) {
  const [since, setSince] = useState(route.since), [until, setUntil] = useState(route.until), [model, setModel] = useState(route.modelUnknown ? '__unknown' : route.model ?? ''), [effort, setEffort] = useState(route.effortUnknown ? '__unknown' : route.effort ?? ''), [zone, setZone] = useState(route.timezone), [error, setError] = useState<'webui.dateInvalid'>();
  return <form onSubmit={e => { e.preventDefault(); try { today(zone); const values = new FormData(e.currentTarget), from = String(values.get('since') ?? since), to = String(values.get('until') ?? until); if (from > to) throw new Error(); apply(kind === 'dates' ? { since: from, until: to, undated: false, allTime: false } : { model: model === '__unknown' ? undefined : model || undefined, modelUnknown: model === '__unknown', effort: effort === '__unknown' ? undefined : effort || undefined, effortUnknown: effort === '__unknown', timezone: zone }); } catch { setError('webui.dateInvalid'); } }}>
    {kind === 'dates' ? <><div className="date-presets"><button type="button" onClick={() => apply({ allTime: true, undated: false })}>{t('webui.allDates')}</button>{[7, 30, 90].map(days => <button type="button" key={days} onClick={() => { const end = today(route.timezone); apply({ since: shiftDate(end, 1 - days), until: end, relativeDays: days, undated: false, allTime: false }); }}>{t('webui.lastDays', { days })}</button>)}</div><div className="filter-grid"><label>{t('webui.since')}<input name="since" type="date" required value={since} onChange={e => setSince(e.target.value)} /></label><label>{t('webui.until')}<input name="until" type="date" required min={since} value={until} onChange={e => setUntil(e.target.value)} /></label></div><p className="note">{route.timezone}</p></> : <><p className="subtle">{t('webui.filterHint')}</p><div className="filter-grid"><label>{t('webui.model')}<select value={model} onChange={e => setModel(e.target.value)}><option value="">{t('webui.allModels')}</option>{[...new Set([...(data?.overview.facets?.models ?? []), ...(route.model ? [route.model] : [])])].map(m => <option key={m}>{m}</option>)}<option value="__unknown">{t('webui.unknown')}</option></select></label><label>{t('webui.effort')}<select value={effort} onChange={e => setEffort(e.target.value)}><option value="">{t('webui.allEfforts')}</option>{data?.overview.facets?.reasoningEfforts.map(f => <option key={f}>{f}</option>)}<option value="__unknown">{t('webui.unknown')}</option></select></label><label>{t('webui.timezone')}<select value={zone} onChange={e => setZone(e.target.value)}>{[...new Set([route.timezone, 'Asia/Shanghai', 'UTC', 'America/Los_Angeles'])].map(z => <option key={z}>{z}</option>)}</select></label></div></>}
    <p role="alert" className="form-error">{error?t(error):''}</p><div className="actions"><button className="primary">{t('webui.apply')}</button></div></form>;
}
