import { t } from '@wombat/client/locale';
import type { UsageResult } from '@wombat/client';
import type { ReactNode } from 'react';
import { directoryName } from '../components.js';
import type { Route } from '../state.js';
interface Props { route: Route; scopeValue: string; dirs: string[]; projectLoads?: NonNullable<UsageResult['freshness']>['projectLoads']; hasUnassigned?: boolean; sourceLabel: string; changeScope: (project?: string, unassigned?: boolean) => void; onSources: () => void; footer?: ReactNode; compact?: boolean }
export function ProjectNavigation({ route, scopeValue, dirs, projectLoads, hasUnassigned, sourceLabel, changeScope, onSources, footer, compact = false }: Props) {
 const state = (project: string | null) => {
  const load = projectLoads?.find(p => p.project === project);
  return load ? t(load.state === 'ready' ? 'webui.projectReady' : load.state === 'loading' ? 'webui.projectLoading' : 'webui.projectPending') : '';
 };
 return compact ? <div className="mobile-scope"><label htmlFor="mobile-project">{t('webui.scope')}</label><select id="mobile-project" value={scopeValue} onChange={e => changeScope(e.target.value.startsWith('directory:') ? e.target.value.slice(10) : undefined, e.target.value === 'unassigned')}><option value="all">{t('webui.all')}</option>{dirs.map(d => <option key={d} value={'directory:' + d}>{directoryName(d)}{state(d) && ' · ' + state(d)}</option>)}{hasUnassigned && <option value="unassigned">{t('webui.unassigned')}{state(null) && ' · ' + state(null)}</option>}</select></div> : <aside className="sidebar" aria-label={t('webui.scope')}><div className="brand"><img src="/wombat.png" alt="" /><span>Wombat<small>{t('webui.tagline')}</small></span></div><div className="sidebar-label">{t('webui.scope')}</div><nav id="projects" aria-label={t('webui.scope')}><button className={`project ${scopeValue === 'all' ? 'active' : ''}`} aria-current={scopeValue === 'all' ? 'true' : undefined} onClick={() => changeScope()}><span className="project-symbol" aria-hidden="true">▦</span>{t('webui.all')}</button>{dirs.length > 0 && <><div className="nav-divider" /><div className="sidebar-label">{t('webui.directory')}</div></>}{dirs.map(dir => <button key={dir} className={`project ${route.project === dir ? 'active' : ''}`} title={dir} aria-current={route.project === dir ? 'true' : undefined} onClick={() => changeScope(dir)}><span className="project-symbol" aria-hidden="true">⌁</span><span className="project-name">{directoryName(dir)}</span>{state(dir) && <small>{state(dir)}</small>}</button>)}{hasUnassigned && <button className={`project ${route.unassigned ? 'active' : ''}`} aria-current={route.unassigned ? 'true' : undefined} onClick={() => changeScope(undefined, true)}><span className="project-symbol" aria-hidden="true">?</span>{t('webui.unassigned')}{state(null) && <small>{state(null)}</small>}</button>}</nav><div className="sidebar-footer"><button className="sidebar-bottom quiet" onClick={() => onSources()}><span className="source-dot" />{t('webui.sources')}<small>{sourceLabel}</small></button>{footer}</div></aside>; }
