// Generated by html-to-opentui compile_visuals.ts. Edit the visual input, then regenerate.
// CSS cascade and state selection are reviewed inputs. Native borders occupy character cells.
type Palette = { "background": string; "controlBorder": string; "fieldBackground": string; "selectedBackground": string; "selectedBorder": string };
export const visualStyles = {
  "period": (palette: Palette) => ({ box: { border: true, borderStyle: "rounded", borderColor: palette["controlBorder"], backgroundColor: palette["background"] }, content: { paddingTop: 0, paddingRight: 1, paddingBottom: 0, paddingLeft: 1, backgroundColor: palette["background"] } } as const),
  "periodActive": (palette: Palette) => ({ box: { borderColor: palette["selectedBorder"], backgroundColor: palette["background"] }, content: { backgroundColor: palette["selectedBackground"] } } as const),
  "metric": (palette: Palette) => ({ box: { border: true, borderStyle: "rounded", borderColor: palette["selectedBorder"], backgroundColor: palette["background"] }, content: { paddingTop: 0, paddingRight: 1, paddingBottom: 0, paddingLeft: 1, backgroundColor: palette["fieldBackground"] } } as const),
};
export const visualAssets = {
  "brand": [
    ".##....##.",
    "##########",
    "##.####.##",
    "##########",
    "###....###",
    "###....###",
    ".###..###.",
    "..######.."
  ]
} as const;
export const visualMonochromeAssets = {
  "brand": "⣾⣳⣶⣞⣷\n⠻⣧⣀⣼⠟"
} as const;
